### PR TITLE
Create mLipok

### PR DESCRIPTION
**Pull request by mlipok**
You can reject my request.
For now I only need it for some test on how GitHub works.

### CODE REVIEW

**Comment by jaberwacky** [comment]
Ok, if you like.  I'm not exactly sure what a pull request is really.

**Comment by mlipok** [comment]
Pull request: if I make a fork and want to be included to main project, then I must make a request.

**Comment by jaberwacky** [comment]
I'm not sure what that means exactly.

**Comment by jaberwacky** [comment]
OK, I did it.  I was afraid I might mess up stuff.

**Pull request merged**
